### ISSUE TITLE
Warning Escher

### ISSUE THREAD

**Issue by AngeloVenera** [AcuGIS/Escher#1]
Hi at all

when i click in button "Escher" i see the all plugin but at end of the page i have this two messages:

Warning: DOMDocument::loadHTML(): Unexpected end tag : head in Entity, line: 99 in /var/www/html/omeka/plugins/Escher/controllers/IndexController.php on line 15

Warning: DOMDocument::loadHTML(): htmlParseStartTag: misplaced <body> tag in Entity, line: 101 in /var/www/html/omeka/plugins/Escher/controllers/IndexController.php on line 15

Ciao Angelo

**Comment by pateljaykesh** [comment]
Hi 

We have updated files. 

Can you try again by downloading new code?

Thanks

**Comment by AngeloVenera** [comment]
Hi

now i haven’t this two warnings.

Thank you

Angelo
