### ISSUE TITLE
Omeka Classic 2.5 Compatability

### ISSUE THREAD

**Issue by ColeDCrawford** [AcuGIS/Escher#2]
Hello,

I'm using Escher v1.0.1 and the recently released Omeka 2.5. When on the plugin page, the dropdown menu for using Escher to install additional plugins does not populate or dropdown. I've tried this on Firefox, Chrome, and Edge with no luck. No error messages in my console. Screenshot attached.
![omeka](https://cloud.githubusercontent.com/assets/16374762/23154429/aab1ea84-f7c2-11e6-92e2-8fb21c2a9627.PNG)

**Comment by DavidGhedini** [comment]
Hi - I am having a look now...

**Comment by Daniel-KM** [comment]
Fixed in #3.
